#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=2.4.39
DIRECTORY=/opt/packages/bedops/$VERSION
LANG=C

singularity exec -B /ocean $DIRECTORY/singularity-bedops-$VERSION.sif bedextract "$@"
