#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity/3.6.3
fi

VERSION=2.4.39
DIRECTORY=/opt/packages/bedops/$VERSION
LANG=C
singularity exec -B /pylon5 $DIRECTORY/singularity-bedops-$VERSION.sif unstarch "$@"
